modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="terraria_reference"
version="0.2.0"
displayName="Terraria Reference"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Warcar"
description='''Mod that adds terraria to minecraft'''

[[dependencies.terraria_reference]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"



[[dependencies.terraria_reference]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

